language: go
go:
  - 1.8
  
go_import_path: k8s.io/gengo

jobs:
  include:
    - stage: Run UT
      script: 
        - find . -name Makefile | xargs -n1 dirname | while read DIR; do make -C $DIR test; done 
        - go test -v ./...
    - stage: Run Examples
      script: 
        - go run ./examples/set-gen/main.go -i k8s.io/gengo/examples/set-gen/sets/types -o ./examples/set-gen/sets --verify-only 
        - go run ./examples/import-boss/main.go -i k8s.io/gengo/... --verify-only
