arch:
  - amd64
  - ppc64le
language: go
go:
  - "1.13"
  - "1.14"
  - tip

go_import_path: k8s.io/gengo

jobs:
  include:
    - stage: Run tests
      script:
        - go test -v ./...
    - stage: Verify examples
      script:
        - go run ./examples/import-boss/main.go -i $(go list k8s.io/gengo/... | grep -v import-boss/tests | paste -sd',' -) --verify-only
